### ISSUE TITLE
Whether 360PanoImage can be generated based on images

### ISSUE THREAD

**Issue by zhanghongyong123456** [ArcherFMY/SD-T2I-360PanoImage#1]
1. image2360PanoImage
2. Use  different models （checkpoint or loras  https://civitai.com/models）
3. Whether the three models are used simultaneously or can be switched separately
![image](https://github.com/ArcherFMY/SD-T2I-360PanoImage/assets/48466610/b7b79a79-35b6-4339-a3ee-25c303aa28a1)

**Comment by ArcherFMY** [comment]
Hi，
1. Actually we have tried to train a model to generate a 360PanoImage from a single perspective Image, and it worked. The simple idea is to first convert the perspective image and put it in the center of a 2:1 360PanoImage, and then generate the other region via outpainting by SD-Inpainting. The Inpainting model should be trained for this 360PanoImage outpainting task.

See one example below
![image](https://github.com/ArcherFMY/SD-T2I-360PanoImage/assets/11482534/ba4f62ad-64e8-46ff-a779-e19e0b08d955)
![image](https://github.com/ArcherFMY/SD-T2I-360PanoImage/assets/11482534/779d698f-8a55-4b71-a6b6-fdc2d6924854)

2. & 3. Currently, The three models are fine-tuned based on the CIVITAI models. So the 'sd-base' can not be changed for generating the low-res 360PanoImage. However, the super-resolution model ('sr-control') is fine-tuned from the controlnet-tile model, so you can try to use the original controlnet-tile model and change the 'sr-base' to any models you like to do the super-resolution task, I think it should work but maybe not good enough.

**Comment by vahidEtt** [comment]
I am looking for the SD-Inpainting model. Did you release it in this repo? I couldn't find it.

**Comment by ArcherFMY** [comment]
> I am looking for the SD-Inpainting model. Did you release it in this repo? I couldn't find it.

Hi,

Sorry for the late reply.  For some reason, the SD-Inpainting model can not be released currently. But it is on the plan.

**Comment by vahidEtt** [comment]
> > I am looking for the SD-Inpainting model. Did you release it in this repo? I couldn't find it.
> 
> Hi,
> 
> Sorry for the late reply. For some reason, the SD-Inpainting model can not be released currently. But it is on the plan.

Thanks. Great work! Well done!

**Comment by ZZYCauchy** [comment]
This is a good work！ 
1. Is the image2panorama based on SD-inpaintingV2?
2. The training dataset SUN360 seems to be no longer available for download,could you provide the relevant download link?

**Comment by ArcherFMY** [comment]
> This is a good work！
> 
> 1. Is the image2panorama based on SD-inpaintingV2?
> 2. The training dataset SUN360 seems to be no longer available for download,could you provide the relevant download link?

1. The weights are initialized from ControlNetV1.1-Tile by changing the "conditioning_channels"=4
2. We suggest finding some high-quality 360 panoramas for free from https://pixexid.com/search/360-panorama

**Comment by ZZYCauchy** [comment]
1、you means the I2P checkpoint is fine-tuned from a text2img checkpoint but not the inpainting checkpoint ？
2、Because I want to carry out related research work but MVDiffusion, panodiff and other work used SUN360 datasets for experiments, which made me very confused. The dataset in http://[sun360.mit.edu](http://sun360.mit.edu/ now can not be found.

**Comment by ArcherFMY** [comment]
> 1、you means the I2P checkpoint is fine-tuned from a text2img checkpoint but not the inpainting checkpoint ？ 2、Because I want to carry out related research work but panodiff and other work used SUN360 datasets for experiments, which made me very confused. The dataset in http://[sun360.mit.edu](http://sun360.mit.edu/ now can not be found.

Yes. The base model is a t2i model, and we achieve the outpainting by the ControlNet.
