### ISSUE TITLE
About the view of Figure 4, 5, 6, 7.

### ISSUE THREAD

**Issue by Mr-Ma-yikun** [ArcherFMY/SD-T2I-360PanoImage#5]
Hello, I think this is a very interesting work! But I have a question. How did you obtain the two views of the same scene as shown in Figure 7? It seems that your code can only generate a single image. Thanks!
![DIRR2 HNH V4TRFB$G)DHWG](https://github.com/ArcherFMY/SD-T2I-360PanoImage/assets/72637909/d5b1ca3e-7201-4480-be49-7f48e173856f)

**Comment by ArcherFMY** [comment]
Hi, the left-top is the generated image, the left-bottom is obtained by moving the leftmost part to the rightmost part, and the right image is the scope at the connected region.
