### ISSUE TITLE
Related work: Cylin-Painting

### ISSUE THREAD

**Issue by xuxy09** [ArcherFMY/SD-T2I-360PanoImage#7]
This work is related to "Cylin-Painting: Seamless 360 Panoramic Image Outpainting and Beyond" (first appeared on arXiv in Apr. 2022: https://arxiv.org/abs/2204.08563, and later accepted in IEEE Transactions on Image Processing 2023: https://ieeexplore.ieee.org/document/10370742).

**Comment by ArcherFMY** [comment]
Hi，
Great Work！Thanks for sharing！
