### ISSUE TITLE
No module named 'diffusers.models.vae'

### ISSUE THREAD

**Issue by zmlee0514** [ArcherFMY/SD-T2I-360PanoImage#8]
I found that 'diffusers.models.vae' has been removed since version 0.25.0. After I reinstall diffusers version 0.24.0, it raises import error again:
cannot import name 'randn_tensor' from 'diffusers.utils' from txt2panoimg/pipeline_base.py
cannot import name 'is_compiled_module' from 'diffusers.utils' from txt2panoimg/pipeline_sr.py
cannot import name 'randn_tensor' from 'diffusers.utils' from txt2panoimg/pipeline_sr.py

Could you provide a more detailed system requirement file?

Thanks

P.S.
module name does not match in the README inference section: 
`from txt2panoimage import Text2360PanoramaImagePipeline`
should be
`from txt2panoimg import Text2360PanoramaImagePipeline`

**Comment by ArcherFMY** [comment]
Hi
I used diffusers version 0.20.0.dev0

**Comment by willy1322** [comment]
how to make it work? got the same error

**Comment by ArcherFMY** [comment]
for the latest version of diffusers users, please try to update the related library path.

e.g., `from diffusers.models.vae import DecoderOutput` to `from diffusers.models.autoencoders.vae import DecoderOutput`,
`from diffusers.utils import is_compiled_module, randn_tensor` to `from diffusers.utils.torch_utils import is_compiled_module, randn_tensor`

**Comment by willy1322** [comment]
thanx for the reply the error is happening  in colab, is there anything i should do in colab?

**Comment by ArcherFMY** [comment]
hi, I updated this repo to diffusers==0.27.2 (latest, 2024-03-25)

**Comment by willy1322** [comment]
this is great thank you. the error is still there though i have reached to dev of the colab and posted about the update. the error im getting is in the screenshot 
![Screenshot 2024-03-25 200340](https://github.com/ArcherFMY/SD-T2I-360PanoImage/assets/46135717/f7c81765-6786-45d1-a13e-3f25b1f6a2bf) anything i should do from my side?

**Comment by ArcherFMY** [comment]
> this is great thank you. the error is still there though i have reached to dev of the colab and posted about the update. the error im getting is in the screenshot ![Screenshot 2024-03-25 200340](https://private-user-images.githubusercontent.com/46135717/316605953-f7c81765-6786-45d1-a13e-3f25b1f6a2bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzMxMjUsIm5iZiI6MTcxMTUzMjgyNSwicGF0aCI6Ii80NjEzNTcxNy8zMTY2MDU5NTMtZjdjODE3NjUtNjc4Ni00NWQxLWExM2UtM2YyNWIxZjZhMmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5NDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MmUzY2JkYjhkZGYwMzc2NjFhNjllN2IxOTY2NjYwNzA5YzhlYTEzYzA5ZmZjYzhmMDUyNDdjNmJkZjI1OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DX0ly9kj_NqGiVjJbxh0vQMgNgF04YCnOibENVwC1sM) anything i should do from my side?

maybe you can try to restart the colab and clone the repo star tover.
