### ISSUE TITLE
Download Link

### ISSUE THREAD

**Issue by umarkhalidAI** [ArcherFMY/SD-T2I-360PanoImage#9]
Do you have any link other than Baidu cloud? Can you upload the weights on the google drive?

**Comment by ArcherFMY** [comment]
You can download the weights from https://huggingface.co/archerfmy0831/sd-t2i-360panoimage

**Comment by ArcherFMY** [comment]
You can download the weights from https://huggingface.co/archerfmy0831/sd-t2i-360panoimage
